name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-audit:
    name: build-and-audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build

      - name: Install bundler-audit
        run: gem install bundler-audit --no-document

      - name: Security audit
        run: |
          bundler-audit update
          bundler-audit check .
